- name: Install Tomcat & Configure
  hosts: all
 # become: yes
  tasks:
    - name: Install Java
      yum:
        name: java 
        state: latest
      become: yes

    - name: Downlaod tomcat tar file
      unarchive:
        src: 
        dest: /home/ec2-user
        remote_src: yes

    - name: Start tomcat 
      shell: nohup /home/ec2-user/apache-tomcat-9.0.2/bin/startup.sh